# Stage 1: Build
FROM rust:1-slim-bookworm AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock ./
COPY api/ api/
COPY pre-processor/ pre-processor/
COPY resources/ resources/

ENV RUSTFLAGS="-C target-cpu=x86-64-v3"
RUN cargo build --release --bin api

# Stage 2: Runtime
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/api /app/api
# index.bin must be present at build time (generated by pre-processor, excluded from git)
COPY index.bin /app/index.bin
COPY --from=builder /usr/src/app/resources/mcc_risk.json /app/resources/mcc_risk.json

EXPOSE 8080

CMD ["./api"]
